var QUESTIONS={
  umum:[
    {q:"Ibu kota Indonesia adalah?",opts:["Jakarta","Surabaya","Bandung","Medan"],ans:0},
    {q:"Berapa jumlah provinsi Indonesia saat ini?",opts:["34","37","38","40"],ans:2},
    {q:"Gunung tertinggi di Indonesia adalah?",opts:["Semeru","Rinjani","Jayawijaya","Kerinci"],ans:2},
    {q:"Bahasa resmi Indonesia adalah?",opts:["Jawa","Sunda","Indonesia","Melayu"],ans:2},
    {q:"Lagu kebangsaan Indonesia adalah?",opts:["Garuda Pancasila","Indonesia Raya","Tanah Airku","Bagimu Negeri"],ans:1},
    {q:"Presiden pertama Indonesia adalah?",opts:["Soeharto","Habibie","Sukarno","Megawati"],ans:2},
    {q:"Sungai terpanjang di Indonesia adalah?",opts:["Kapuas","Barito","Musi","Mahakam"],ans:0},
    {q:"Hari kemerdekaan Indonesia diperingati pada?",opts:["17 Agustus","17 Juli","17 September","17 Oktober"],ans:0},
    {q:"Mata uang Indonesia adalah?",opts:["Ringgit","Rupiah","Baht","Peso"],ans:1},
    {q:"Pulau terbesar di Indonesia adalah?",opts:["Jawa","Kalimantan","Sulawesi","Sumatra"],ans:1},
    {q:"Pancasila terdiri dari berapa sila?",opts:["3","4","5","6"],ans:2},
    {q:"Burung apakah lambang negara Indonesia?",opts:["Elang","Rajawali","Garuda","Cendrawasih"],ans:2},
  ],
  sains:[
    {q:"Unsur kimia dengan simbol 'O' adalah?",opts:["Osmium","Oksigen","Emas","Besi"],ans:1},
    {q:"Planet terdekat dengan Matahari adalah?",opts:["Venus","Mars","Merkurius","Bumi"],ans:2},
    {q:"Berapa jumlah tulang pada tubuh manusia dewasa?",opts:["196","206","216","226"],ans:1},
    {q:"Air mendidih pada suhu berapa derajat Celsius?",opts:["90°","95°","100°","105°"],ans:2},
    {q:"DNA singkatan dari?",opts:["Deoxyribonucleic Acid","Dibenzyl Nucleic Acid","Direct Nucleic Acid","Dextrose Nucleic Acid"],ans:0},
    {q:"Kecepatan cahaya kira-kira?",opts:["200.000 km/s","300.000 km/s","400.000 km/s","500.000 km/s"],ans:1},
    {q:"Hewan mamalia terbesar di dunia adalah?",opts:["Gajah Afrika","Paus Biru","Hiu Paus","Jerapah"],ans:1},
    {q:"Rumus kimia air adalah?",opts:["H2O","CO2","NaCl","O2"],ans:0},
    {q:"Berapa jumlah kromosom manusia normal?",opts:["23","44","46","48"],ans:2},
    {q:"Gravitasi bumi kira-kira?",opts:["8.8 m/s²","9.8 m/s²","10.8 m/s²","11.8 m/s²"],ans:1},
    {q:"Gas yang paling banyak di atmosfer bumi adalah?",opts:["Oksigen","Argon","Nitrogen","Karbon Dioksida"],ans:2},
    {q:"Berapa jumlah planet di tata surya?",opts:["7","8","9","10"],ans:1},
  ],
  sejarah:[
    {q:"Perang Dunia II berakhir pada tahun?",opts:["1943","1944","1945","1946"],ans:2},
    {q:"Tembok Berlin runtuh pada tahun?",opts:["1987","1988","1989","1990"],ans:2},
    {q:"Siapa yang menemukan benua Amerika?",opts:["Vasco da Gama","Columbus","Magellan","Marco Polo"],ans:1},
    {q:"Revolusi Prancis terjadi pada tahun?",opts:["1776","1789","1800","1815"],ans:1},
    {q:"Kerajaan Majapahit berdiri pada abad ke?",opts:["11","12","13","14"],ans:2},
    {q:"Piramida Giza dibangun oleh bangsa?",opts:["Romawi","Yunani","Mesir","Persia"],ans:2},
    {q:"Siapa penemu telepon?",opts:["Edison","Tesla","Bell","Marconi"],ans:2},
    {q:"Perang Diponegoro berlangsung pada tahun?",opts:["1820-1825","1825-1830","1830-1835","1835-1840"],ans:1},
    {q:"Siapa yang menulis buku 'Bumi Manusia'?",opts:["Chairil Anwar","Pramoedya Ananta Toer","WS Rendra","Sapardi"],ans:1},
    {q:"Proklamasi kemerdekaan Indonesia dibacakan di?",opts:["Lapangan Merdeka","Istana Negara","Jl. Pegangsaan Timur 56","Monas"],ans:2},
    {q:"Siapa penemu bola lampu?",opts:["Newton","Einstein","Edison","Faraday"],ans:2},
    {q:"Perang Dunia I dimulai pada tahun?",opts:["1912","1913","1914","1915"],ans:2},
  ],
  hiburan:[
    {q:"Film 'Laskar Pelangi' diadaptasi dari novel karya?",opts:["Habiburrahman","Andrea Hirata","Dee Lestari","Tere Liye"],ans:1},
    {q:"Boyband asal Korea yang membawakan 'Dynamite'?",opts:["EXO","GOT7","BTS","NCT"],ans:2},
    {q:"Game 'Mobile Legends' dikembangkan oleh?",opts:["Tencent","Moonton","Garena","Supercell"],ans:1},
    {q:"Karakter utama dalam anime 'Naruto' adalah?",opts:["Sasuke","Sakura","Naruto Uzumaki","Kakashi"],ans:2},
    {q:"'Avengers: Endgame' dirilis pada tahun?",opts:["2017","2018","2019","2020"],ans:2},
    {q:"Aplikasi video pendek 'TikTok' berasal dari negara?",opts:["Jepang","Korea","Amerika","China"],ans:3},
    {q:"Siapa pencipta karakter 'Mickey Mouse'?",opts:["Steven Spielberg","Walt Disney","Tim Burton","James Cameron"],ans:1},
    {q:"Seri game 'GTA' dibuat oleh?",opts:["EA Games","Ubisoft","Rockstar Games","Blizzard"],ans:2},
    {q:"'Harry Potter' ditulis oleh?",opts:["J.R.R. Tolkien","C.S. Lewis","J.K. Rowling","George R.R. Martin"],ans:2},
    {q:"Platform streaming 'Netflix' berpusat di?",opts:["New York","Los Gatos","San Francisco","Seattle"],ans:1},
    {q:"Anime 'One Piece' dibuat oleh?",opts:["Masashi Kishimoto","Eiichiro Oda","Akira Toriyama","Hajime Isayama"],ans:1},
    {q:"Game 'Minecraft' awalnya dibuat oleh?",opts:["Valve","Mojang","Epic Games","Bethesda"],ans:1},
  ],
  teknologi:[
    {q:"CPU singkatan dari?",opts:["Central Processing Unit","Computer Processing Unit","Central Program Unit","Core Processing Unit"],ans:0},
    {q:"Siapa pendiri Microsoft?",opts:["Steve Jobs","Elon Musk","Bill Gates","Mark Zuckerberg"],ans:2},
    {q:"HTML singkatan dari?",opts:["Hyper Text Markup Language","High Text Markup Language","Hyper Transfer Markup Language","Hyper Text Machine Language"],ans:0},
    {q:"Sistem operasi Android dikembangkan oleh?",opts:["Apple","Microsoft","Google","Samsung"],ans:2},
    {q:"Bahasa pemrograman yang digunakan untuk membuat website?",opts:["Python","Java","JavaScript","C++"],ans:2},
    {q:"RAM singkatan dari?",opts:["Random Access Memory","Read Access Memory","Rapid Access Memory","Run Access Memory"],ans:0},
    {q:"Siapa pendiri Facebook (Meta)?",opts:["Steve Jobs","Larry Page","Mark Zuckerberg","Jack Dorsey"],ans:2},
    {q:"WWW singkatan dari?",opts:["World Wide Web","World Width Web","Wide World Web","World Web Wide"],ans:0},
    {q:"Perangkat keras untuk menyimpan data permanen adalah?",opts:["RAM","ROM","CPU","GPU"],ans:1},
    {q:"Bahasa pemrograman Python diciptakan oleh?",opts:["James Gosling","Guido van Rossum","Brendan Eich","Dennis Ritchie"],ans:1},
    {q:"iPhone pertama diluncurkan pada tahun?",opts:["2005","2006","2007","2008"],ans:2},
    {q:"USB singkatan dari?",opts:["Universal Serial Bus","Unified Serial Bus","Universal System Bus","Unified System Bus"],ans:0},
  ],
  matematika:[
    {q:"Berapa hasil dari 15 × 15?",opts:["175","200","225","250"],ans:2},
    {q:"Akar kuadrat dari 144 adalah?",opts:["11","12","13","14"],ans:1},
    {q:"Berapa nilai π (pi) yang paling tepat?",opts:["3.14","3.12","3.16","3.18"],ans:0},
    {q:"Jika x + 7 = 15, berapa nilai x?",opts:["6","7","8","9"],ans:2},
    {q:"Berapa hasil dari 2⁸ (2 pangkat 8)?",opts:["128","256","512","64"],ans:1},
    {q:"Segitiga dengan ketiga sisi sama panjang disebut?",opts:["Siku-siku","Sama kaki","Sama sisi","Sembarang"],ans:2},
    {q:"Berapa jumlah sudut dalam sebuah segi enam?",opts:["540°","620°","720°","800°"],ans:2},
    {q:"Bilangan prima antara 10 dan 20 adalah?",opts:["11,13,17,19","11,15,17,19","11,13,15,19","13,15,17,19"],ans:0},
    {q:"Berapa hasil dari 1000 ÷ 25?",opts:["35","40","45","50"],ans:1},
    {q:"Luas lingkaran jari-jari 7 cm? (π=22/7)",opts:["144 cm²","154 cm²","164 cm²","174 cm²"],ans:1},
    {q:"Berapa hasil dari 17 × 8?",opts:["126","136","146","156"],ans:1},
    {q:"Berapa FPB dari 24 dan 36?",opts:["6","8","12","18"],ans:2},
  ],
  geografi:[
    {q:"Benua terluas di dunia adalah?",opts:["Afrika","Amerika","Asia","Eropa"],ans:2},
    {q:"Sungai terpanjang di dunia adalah?",opts:["Amazon","Mississippi","Nil","Yangtze"],ans:2},
    {q:"Ibu kota Australia adalah?",opts:["Sydney","Melbourne","Brisbane","Canberra"],ans:3},
    {q:"Gunung tertinggi di dunia adalah?",opts:["K2","Kangchenjunga","Everest","Lhotse"],ans:2},
    {q:"Negara dengan luas wilayah terbesar di dunia adalah?",opts:["Amerika Serikat","China","Kanada","Rusia"],ans:3},
    {q:"Danau terdalam di dunia adalah?",opts:["Danau Superior","Danau Baikal","Danau Titicaca","Danau Victoria"],ans:1},
    {q:"Selat yang memisahkan Pulau Jawa dan Sumatra?",opts:["Selat Malaka","Selat Sunda","Selat Lombok","Selat Madura"],ans:1},
    {q:"Ibu kota Brasil adalah?",opts:["São Paulo","Rio de Janeiro","Salvador","Brasília"],ans:3},
    {q:"Pegunungan Himalaya berada di benua?",opts:["Afrika","Amerika","Asia","Eropa"],ans:2},
    {q:"Negara dengan jumlah penduduk terbanyak di dunia?",opts:["India","China","Amerika","Indonesia"],ans:0},
    {q:"Ibu kota Jepang adalah?",opts:["Osaka","Kyoto","Tokyo","Nagoya"],ans:2},
    {q:"Gurun terluas di dunia adalah?",opts:["Sahara","Gobi","Arabia","Antartika"],ans:3},
  ],
  kuliner:[
    {q:"Rendang berasal dari daerah?",opts:["Jawa Barat","Sulawesi Selatan","Sumatra Barat","Bali"],ans:2},
    {q:"Sushi adalah makanan khas negara?",opts:["China","Korea","Jepang","Thailand"],ans:2},
    {q:"Pizza berasal dari negara?",opts:["Prancis","Italia","Spanyol","Portugal"],ans:1},
    {q:"Bahan utama pembuatan tempe adalah?",opts:["Kacang tanah","Kedelai","Jagung","Singkong"],ans:1},
    {q:"Nasi Padang berasal dari provinsi?",opts:["Riau","Jambi","Sumatra Barat","Sumatra Utara"],ans:2},
    {q:"Makanan khas Yogyakarta yang terkenal adalah?",opts:["Pempek","Gudeg","Rawon","Papeda"],ans:1},
    {q:"Tom Yum adalah sup khas dari negara?",opts:["Vietnam","Malaysia","Thailand","Filipina"],ans:2},
    {q:"Keju sebagian besar dibuat dari bahan?",opts:["Susu","Telur","Terigu","Kedelai"],ans:0},
    {q:"Makanan 'Pempek' berasal dari kota?",opts:["Medan","Palembang","Bandung","Makassar"],ans:1},
    {q:"Cokelat pertama kali berasal dari biji tanaman?",opts:["Kopi","Kakao","Vanila","Kapulaga"],ans:1},
    {q:"Makanan khas Bali yang terkenal adalah?",opts:["Babi Guling","Rendang","Soto","Bakso"],ans:0},
    {q:"Minuman khas Indonesia yang terbuat dari ketan?",opts:["Tuak","Brem","Tape","Cendol"],ans:1},
  ],
  olahraga:[
    {q:"Berapa jumlah pemain dalam satu tim sepak bola?",opts:["9","10","11","12"],ans:2},
    {q:"Olahraga bulu tangkis disebut juga?",opts:["Tennis","Badminton","Squash","Ping Pong"],ans:1},
    {q:"Olimpiade modern pertama kali diadakan di?",opts:["Paris","London","Athena","Roma"],ans:2},
    {q:"Siapa pemain sepak bola dengan julukan 'La Pulga'?",opts:["Ronaldo","Neymar","Messi","Mbappé"],ans:2},
    {q:"Berapa set dalam pertandingan tenis Grand Slam putra?",opts:["3","4","5","6"],ans:2},
    {q:"Olahraga renang gaya kupu-kupu disebut juga?",opts:["Crawl","Backstroke","Butterfly","Breaststroke"],ans:2},
    {q:"Kejuaraan golf tertua di dunia disebut?",opts:["The Open","US Open","The Masters","PGA Championship"],ans:0},
    {q:"Berapa poin untuk three-pointer dalam basket?",opts:["1","2","3","4"],ans:2},
    {q:"Negara asal olahraga sumo adalah?",opts:["China","Korea","Jepang","Mongolia"],ans:2},
    {q:"Piala Dunia FIFA pertama kali diadakan pada tahun?",opts:["1926","1928","1930","1934"],ans:2},
    {q:"Berapa tinggi net dalam permainan voli putra?",opts:["2.24 m","2.34 m","2.43 m","2.53 m"],ans:2},
    {q:"Olahraga yang menggunakan stik dan bola kecil di atas es?",opts:["Curling","Polo","Lacrosse","Hoki Es"],ans:3},
  ],
  musik:[
    {q:"Alat musik gitar termasuk ke dalam kelompok?",opts:["Perkusi","Melodis","Harmonis","Chordofon"],ans:3},
    {q:"Lagu 'Bohemian Rhapsody' dipopulerkan oleh band?",opts:["The Beatles","Queen","Led Zeppelin","Pink Floyd"],ans:1},
    {q:"Not musik yang paling tinggi di antara ini adalah?",opts:["Do","Mi","Sol","Si"],ans:3},
    {q:"Alat musik piano termasuk ke dalam kelompok?",opts:["String","Wind","Percussion","Keyboard"],ans:3},
    {q:"Penyanyi yang dijuluki 'King of Pop' adalah?",opts:["Elvis Presley","Michael Jackson","Prince","David Bowie"],ans:1},
    {q:"Alat musik tradisional Jawa yang terbuat dari bambu?",opts:["Angklung","Gamelan","Suling","Kendang"],ans:2},
    {q:"Lagu 'Imagine' diciptakan oleh?",opts:["Paul McCartney","John Lennon","George Harrison","Ringo Starr"],ans:1},
    {q:"Genre musik yang berasal dari Amerika dengan irama blues?",opts:["Pop","Rock","Jazz","Classical"],ans:2},
    {q:"Alat musik angklung berasal dari daerah?",opts:["Jawa Tengah","Bali","Jawa Barat","Sulawesi"],ans:2},
    {q:"Penyanyi 'Shape of You' adalah?",opts:["Justin Bieber","Bruno Mars","Ed Sheeran","Charlie Puth"],ans:2},
    {q:"Alat musik yang dimainkan dengan cara ditiup?",opts:["Biola","Saksofon","Gitar","Piano"],ans:1},
    {q:"Band legendaris asal Inggris 'The Beatles' berasal dari kota?",opts:["London","Manchester","Liverpool","Birmingham"],ans:2},
  ],
};

// Daily challenge pool (fixed seed per day)
function getDailyQuestions() {
  const today = new Date().toDateString();
  const seed = today.split('').reduce((a,c)=>a+c.charCodeAt(0),0);
  const allQ = Object.values(QUESTIONS).flat();
  const rng = (s) => { let x=Math.sin(s)*10000; return x-Math.floor(x); };
  const shuffled = [...allQ].sort((a,b)=>rng(seed+allQ.indexOf(a))-rng(seed+allQ.indexOf(b)));
  return shuffled.slice(0,10);
}
